# Generated by Django 4.0.5 on 2022-08-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chice',
            new_name='Choice',
        ),
    ]
